### ISSUE TITLE
Using https fails

### ISSUE THREAD

**Issue by cmdcolin** [habeducation/habeducation.github.io#15]
Might be nice to have https://hab.education but it currently times out

Not sure if related https://github.com/isaacs/github/issues/156

**Comment by htruong** [comment]
From what I understand, this might not be an easy answer, basically .github.io will work, but since we have a custom domain, we have to take more steps. We can make this work if we really need to, but I'd rather keep it in "list of things to do" :) What you think?

**Comment by cmdcolin** [comment]
Seems fine, other sites seem to address by moving to new host or something, so just keep as is
