### ISSUE TITLE
Find alternate host for images

### ISSUE THREAD

**Issue by cmdcolin** [habeducation/habeducation.github.io#2]
There are about 300MB of images in the repo

That is duplicated in the .git directory making on total size 600MB on my HD

Too big IMO

**Comment by cmdcolin** [comment]
Goes to 900MB after jekyll serve is run since this copies the resources

**Comment by htruong** [comment]
Agreed, actually I think we could have a resize script to resize the images before uploading. Let me figure something out.

**Comment by htruong** [comment]
Refer to #8 ... Would that be a sane idea?

**Comment by dmayfieldjones** [comment]
any new ideas?

**Comment by cmdcolin** [comment]
Removed the images/GPSL files

Everyone should re-clone the repo instead of trying to git pull as removing those files is a repo destructive operation

**Comment by cmdcolin** [comment]
I don't think it worked to reduce repo size. I just used git filter-branch. Might need to pull out BFG >_<

**Comment by htruong** [comment]
I will go ahead and clean up the repository now.

**Comment by htruong** [comment]
@cmdcolin Do you have any branches that are in use, if not let me delete them so that we don't have to deal with them?

**Comment by cmdcolin** [comment]
nope. can delete

**Comment by htruong** [comment]
Cleaned. It is now only 27MB, I'd say I am pretty happy with it.

```
Receiving objects: 100% (1862/1862), 27.36 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (1005/1005), done.
```

**Comment by htruong** [comment]
I put the images for mjwebsitetransfer to Google Drive and cleaned all of them. Danny Bowman's images are resized to 1280. Original images are moved to Google Drive.

I also removed the sauce PSD file and moved to  Google Drive.

**Comment by cmdcolin** [comment]
so much better :)

**Comment by htruong** [comment]
Bloody h@ll, @cmdcolin now all the commits are duplicated for some reason... The commit graph looks like this, do you know how to get rid of the duplicated ones: 

https://github.com/habeducation/habeducation.github.io/network

**Comment by cmdcolin** [comment]
hmm. did u do any force pushes today that might have caused it?

**Comment by cmdcolin** [comment]
I have a full mirror of the repo (git clone --mirror) from when I did the git filter branch that I could check

**Comment by htruong** [comment]
I obviously did a force push because I rewrote the history. Either way it's not important, just somewhat annoying when we look back :)

**Comment by cmdcolin** [comment]
@htruong ya. Did you happen to have done a fresh clone before you did the force push? Because I also did a force push over history when I did filter branch?

**Comment by htruong** [comment]
It's compacted so no longer an issue :)
