### ISSUE TITLE
Community support

### ISSUE THREAD

**Issue by dmayfieldjones** [habeducation/habeducation.github.io#26]
Topics that need follow up conversations from the 2016 HAB Educator Summit:

Sustainable tracking options: 1.
Building the trackuino info and workshop: 2.
Share community contacts: See attached.
Share presentation: See attached.

Student leadership: 4.
New HAB educator interest workshop: 5.
HAB festival: 6

**Comment by cmdcolin** [comment]
Added some disqus forums here http://hab.education/pages/discussion.html

**Comment by htruong** [comment]
I applause your creativity, guys

**Comment by cmdcolin** [comment]
+1

if we get really crazy, then arbitrary topics can be created too. cool demo http://klcodanr.github.io/Jekyll-Disqus-Forum/

**Comment by cmdcolin** [comment]
Can add new discussions as needed I think. I didn't anticipate a big amount of discussion on these pages tho. Generally disqus is kind of "Drive by commentary" rather than centralized discussion
