### ISSUE TITLE
Change bash to gulp/whatever build?

### ISSUE THREAD

**Issue by htruong** [habeducation/habeducation.github.io#6]
Hey @cmdcolin, currently I'm generating the compacted header (with css built-in) by doing a bash script that calls another online css compactor, it doesn't integrate with the rest of the system too well. I am not familiar with gulp or anything else (rb?) so that we have a more streamlined system.

Any ideas?

**Comment by cmdcolin** [comment]
Maybe we can try gulp-inline-css or gulp-inline-source
I think that will take a plain HTML file with links to externals and inline them. It also has nice minification tools

**Comment by cmdcolin** [comment]
Fixed by #16!
