### ISSUE TITLE
Validate AMP spec

### ISSUE THREAD

**Issue by htruong** [habeducation/habeducation.github.io#7]
Activate the dev mode on AMP by visiting http://hab.education/#development=1

AMP validator said that we can't do styling on the a tag on front page

```
    <a class="tab" href="/2016/04/28/more-d3-wgraphs.html" style="background-image: url('https://twitter.com/balloonedu/profile_image?size=bigger');">
```

Because the post template uses the post.thumb to render the post thumbnail.

I wonder if there is a better way to get this done.

**Comment by htruong** [comment]
Out of insomnia, I got this fixed.

**Comment by cmdcolin** [comment]
ccrazy!

**Comment by dmayfieldjones** [comment]
Crazy

**Comment by htruong** [comment]
This would promote our search result on Google as well. Hey @cmdcolin, can you give me and Dustin access to Google Analytics?

**Comment by htruong** [comment]
My email is huant at tnhh dotttt net. Dustin is dustin at mayfieldjones dotttt com.

**Comment by cmdcolin** [comment]
you guys should be added. I added those with permissions

**Comment by cmdcolin** [comment]
ill edit ur emails away actually just to avoid ur spam filters :)

**Comment by htruong** [comment]
Got it. Thanks!
