### ISSUE TITLE
Static image host right here

### ISSUE THREAD

**Issue by htruong** [habeducation/habeducation.github.io#8]
Here we create an issue where we drop all of our asset images, to get their URLs and serve it from our website so we don't track them anymore.

**Comment by htruong** [comment]
![background](https://cloud.githubusercontent.com/assets/146489/15725572/2b6de74e-2812-11e6-9342-e3afb81f22ce.jpg)
![background-mobile](https://cloud.githubusercontent.com/assets/146489/15725573/2b6dfdf6-2812-11e6-9c79-276728fd2b42.jpg)
![dustin_edu](https://cloud.githubusercontent.com/assets/146489/15725577/2b7d07ce-2812-11e6-8460-80d9656605e6.jpg)
![dustinhuan_edu](https://cloud.githubusercontent.com/assets/146489/15725576/2b7cab80-2812-11e6-8a37-daf997967b60.jpg)
![group_hab0](https://cloud.githubusercontent.com/assets/146489/15725574/2b7aafd8-2812-11e6-9f3f-d69804350829.jpg)
![huan_edu](https://cloud.githubusercontent.com/assets/146489/15725575/2b7bf244-2812-11e6-83ad-b0dfa69f1191.jpg)
![icon](https://cloud.githubusercontent.com/assets/146489/15725579/2b888a04-2812-11e6-8d42-00d7185b3a08.png)
![talk](https://cloud.githubusercontent.com/assets/146489/15725578/2b843fbc-2812-11e6-9738-3822e5dd0041.jpg)

**Comment by cmdcolin** [comment]
Not sure. I think this trick is nice but I have seen github issue images go away. E.g. this thread https://github.com/GMOD/jbrowse/issues/569

Kind of worrisome

**Comment by htruong** [comment]
Ah I see. So maybe this idea needs to be abandoned.

**Comment by cmdcolin** [comment]
The largest contributor is this https://github.com/habeducation/habeducation.github.io/tree/master/images/GPSL

Good photos but should probably be given a dedicated host

**Comment by cmdcolin** [comment]
After deleting them, we can use BFG to delete files from the past repo history http://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

That is a destructive operation and requires a force push and then the repo size will be smaller again.

**Comment by dmayfieldjones** [comment]
i just saw this now.

**Comment by cmdcolin** [comment]
@dmayfieldjones ya convo got spread over multiple issues. I think the bfg approach is good though
